CC = g++
QMAKE = qmake
RMR = rm -Rf
RM = rm -f
MAKE = make

LOCATION = `pwd`
SRC_DIR = ./src
BUILD_DIR = build

AGENT_DIR = $(SRC_DIR)/MonitoringAgent/
MASTER_DIR = $(SRC_DIR)/MonitoringMaster/
CLIENT_DIR = $(SRC_DIR)/MonitoringProcesses/
