#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          MonitoringMasterScript
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init and stop script for the MonitoringMaster Daemon
# Description:       This file should be used to start and stop the
#                    Daemon that corresponds to the MonitoringMaster
### END INIT INFO

# Author: Jose Manuel Abuin Mosquera <josemanuel.abuin@usc.es>
#

DESC="Service to launch or stop the MonitoringMaster Daemon"
DAEMON=/usr/bin/MonitoringMaster


